CREATE TABLE profile_image (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    `url` VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(id)
);